# Generated by Django 5.2.3 on 2026-02-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.FileField(blank=True, max_length=500, null=True, upload_to='receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applicants.applicant')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='payments_applica_72c3c0_idx')],
            },
        ),
    ]
