# Generated by Django 5.2.3 on 2026-02-02 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True, help_text='Current residential address')),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('visa_type', models.CharField(blank=True, max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('docs_pending', 'Docs Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Dynamic fields for specific visa requirements')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(help_text='The partner company that owns this applicant.', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='accounts.partner')),
            ],
            options={
                'db_table': 'applicants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['partner', 'status'], name='applicants_partner_d3b8a2_idx'), models.Index(fields=['partner', 'passport_number'], name='applicants_partner_7c98d7_idx'), models.Index(fields=['partner', 'created_at'], name='applicants_partner_f01994_idx')],
            },
        ),
    ]
