# Generated by Django 5.2.3 on 2026-02-10 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applicants', '0002_add_applicant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_user',
            field=models.ForeignKey(blank=True, help_text='If set, this User owns this applicant profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='The partner company that owns this applicant. Null for self-registered applicants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='accounts.partner'),
        ),
    ]
