# Generated by Django 5.2.3 on 2026-02-20 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_remove_token_blacklist_tables'),
        ('applicants', '0003_alter_applicant_applicant_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visa_type', models.CharField(blank=True, help_text='e.g., Tourist, Business, Work', max_length=100)),
                ('destination_country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('docs_pending', 'Docs Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('partner_notes', models.TextField(blank=True, help_text='Notes visible to partner')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (staff only)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(help_text='The applicant this deal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='applicants.applicant')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to this deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(help_text='Partner who created this deal', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='accounts.partner')),
            ],
            options={
                'db_table': 'deals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='If true, only staff can see')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_notes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='deals.deal')),
            ],
            options={
                'db_table': 'deal_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['partner', 'status'], name='deals_partner_debebe_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['partner', 'payment_status'], name='deals_partner_f915ba_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['partner', 'created_at'], name='deals_partner_47882f_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['applicant'], name='deals_applica_e738b6_idx'),
        ),
    ]
