# Generated by Django 5.2.3 on 2026-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('partner', 'Partner'), ('applicant', 'Applicant'), ('staff', 'Staff'), ('admin', 'Admin')], default='partner', max_length=20),
        ),
    ]
