# Generated by Django 5.2.3 on 2026-02-18 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_emailverification_teaminvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
