# Generated by Django 5.2.3 on 2026-02-02 20:30

import django.core.validators
import django.db.models.deletion
import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('passport', 'Passport Scan'), ('photo', 'Passport Photo'), ('bank_statement', 'Bank Statement'), ('ticket', 'Flight Ticket'), ('insurance', 'Travel Insurance'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(help_text='Allowed formats: PDF, JPG, PNG, DOC, DOCX', max_length=500, upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('original_filename', models.CharField(blank=True, help_text='Original name of the uploaded file', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(help_text='The applicant this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicants.applicant')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['applicant', 'status'], name='documents_applica_485726_idx'), models.Index(fields=['applicant', 'document_type'], name='documents_applica_81dd19_idx')],
            },
        ),
    ]
