# Generated by Django 5.2.3 on 2026-02-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base percentage (e.g., 5.00 for 5%)', max_digits=5)),
                ('bonus_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra percentage if threshold is met', max_digits=5)),
                ('threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Deal value amount required to trigger the bonus', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Rule',
                'verbose_name_plural': 'Commission Rules',
                'db_table': 'commission_rules',
                'ordering': ['base_rate'],
            },
        ),
        migrations.AlterField(
            model_name='commission',
            name='payout_reference',
            field=models.CharField(blank=True, help_text='Transaction ID or Check #', max_length=100),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
